paths:
  /api/products:
    get:
      summary: Obtener a todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Products"
        "500": Error interno del servidor
  /api/products/{:pid}:
    get:
      summary: Obtener un producto en especifico
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: ID del producto a buscar
      responses:
        "200":
          description: Producto obtenido correctamente
          content:
            application/json:
              schema:
                type: array
        "500": Error interno del servidor

components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDB
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        thumbnail:
          type: Array
          description: Imagen del producto
        code:
          type: Number
          description: Codigo del producto
        Stock:
          type: Number
          description: Stock del producto
        Category:
          type: String
          description: Categoria del producto
      example:
        _id: 6549e73474ac2f46b11f193b,
        title: Nike Air Max,
        description: Zapatillas Nike Negras Air Max,
        price: $400.000,
        thumbnail: []
        code: 332,
        stock: 24,
        category: Zapatillas
